//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// IPScanUtil.rc에서 사용되고 있습니다.
//
#define IDCANCEL                        2
#define ID_FACTORY_DEFAULT_BTN          3
#define ID_FACTORY_DEFAULT_CANCEL       4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_LISTVIEW_EDIT               101
#define IDD_IPSCANUTIL_DIALOG           102
#define IDS_ADDRESS                     102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_PORT                        104
#define IDS_STREAM                      105
#define IDS_STATUS_SCANNING             106
#define IDS_STATUS_STOP                 107
#define IDS_STOP                        108
#define IDS_SCAN                        109
#define IDS_IP_CHANGE                   110
#define IDS_MEMORY                      111
#define IDS_RECEIVE_FAILED              112
#define IDS_BIND_FAILED                 113
#define IDS_UNKNOWN_ERROR               114
#define IDS_SOCKET_ERROR                115
#define IDS_ENTER_LOGIN_INFO            116
#define IDS_FIRMWARE_VERSION            117
#define IDS_MODEL                       118
#define IDS_SERVER_NAME                 119
#define IDS_N_AND_A                     120
#define IDS_RESOLUTIONS                 121
#define IDS_VIDEO_FORMAT                122
#define IDS_ALARM_IN_COUNT              123
#define IDS_ALARM_OUT_COUNT             124
#define IDS_AUDIO_IN_COUNT              125
#define IDS_AUDIO_OUT_COUNT             126
#define IDS_UPGRADE_PROGRESS            127
#define IDR_MAINFRAME                   128
#define IDS_ENTER_PASSWORD_INFO         128
#define IDD_CAM_IPCHANGE                129
#define IDS_USER_ID                     129
#define IDR_MENU1                       130
#define IDS_USER_PW                     130
#define IDR_POPUP_MENU                  131
#define IDS_DHCP                        131
#define IDD_UPGRADE_BTN                 132
#define IDS_STATIC                      132
#define IDR_POPUP_MENU_UPGRADE          132
#define IDD_UPGRADE                     133
#define IDB_CHECKBOXES                  133
#define IDS_IP_TYPE                     133
#define IDS_PROGRESS_STATUS             134
#define IDD_CAM_IPCHANGE2               134
#define IDD_FACTORYDEFAULT              135
#define IDS_STREAM_CHECK                135
#define IDS_EVENT_CHECK                 136
#define IDS_DIFFERENT_BAND              137
#define IDD_CAM_RESOLCHANGE             137
#define IDS_MCU_VERSION                 138
#define IDD_CAM_OSDCHANGE               138
#define IDS_MCU_MODEL                   139
#define IDS_SW_VERSION                  140
#define IDS_VIDEO_COUNT                 141
#define IDS_BASE_PORT                   142
#define IDC_SVR_LIST                    1000
#define IDC_SCAN_BTN                    1001
#define IDC_CHANGEIP_BTN                1002
#define IDC_STATIC_STATUES              1003
#define IDC_CLOSE                       1005
#define IDC_CLEAR_BTN                   1006
#define IDC_STC_SNUM                    1007
#define IDC_TEST_BTN                    1008
#define IDC_UPGRADE_BTN                 1009
#define IDC_FACTORY_BTN                 1010
#define IDC_LIST2                       1011
#define IDC_UPGRADE_LIST                1011
#define IDC_TEST_BTN2                   1011
#define IDC_OPENFILE_BTN                1015
#define IDC_OPENFILE_EDIT               1016
#define IDC_PROGRESS1                   1019
#define IDC_UPGRADE_USERID              1023
#define IDC_UPGRADE_PASSWORD            1024
#define IDC_STC_UPGRADE_LOGIN           1025
#define IDC_STC_UPGRADE_USERID          1026
#define IDC_STC_UPGRADE_PASSWORD        1027
#define IDC_STC_MODEL                   1028
#define IDC_MODEL_COMBO                 1029
#define IDC_START_IPADDR                1031
#define IDC_STATIC_START_IPADDR         1032
#define IDC_STC_PROCESSING              1033
#define IDC_PROTOCAL_COMBO              1035
#define IDC_STATIC_VERSION              1036
#define IDC_CHECK2                      1038
#define IDC_CHECK_ALL                   1038
#define IDC_COMBO2                      1041
#define IDC_ADAPTOR_CMB                 1041
#define IDC_STATIC_NETWORK              1042
#define IDC_STATIC_PROGRAME_INFO        1043
#define IDC_STATIC_PROGRAME_INFO2       1044
#define IDC_COMBO_STREAMTYPE            1044
#define IDC_SLIDER_BITRATE1             1045
#define IDC_EDIT_BITRATE1               1046
#define IDC_COMBO_CODECTYPE             1047
#define IDC_COMBO_RESOLUTION            1048
#define IDC_COMBO_RATECONTROL           1049
#define IDC_COMBO_FPS1                  1050
#define IDC_COMBO_GOP1                  1051
#define IDC_SLIDER_BITRATE2             1052
#define IDC_COMBO_FPS2                  1053
#define IDC_COMBO_GOP2                  1054
#define IDC_EDIT_BITRATE2               1055
#define IDC_COMBO_MJPEG_QUALITY         1056
#define IDC_COMBO_MJPEG_FPS             1057
#define IDC_STATIC_GROUP_STREAM1        1058
#define IDC_STATIC_GROUP_STREAM2        1059
#define IDC_STATIC_GROUP_MJPEG          1060
#define IDC_STATIC_STREAMTYPE           1061
#define IDC_STATIC_CODEC                1062
#define IDC_STATIC_RESOLUTION           1063
#define IDC_STATIC_RATECONTROL          1064
#define IDC_STATIC_QUALITY              1065
#define IDC_STATIC_FRAMERATE            1066
#define IDC_STATIC_BITRATE1             1067
#define IDC_STATIC_BITRATE2             1068
#define IDC_STATIC_FRAMERATE1           1069
#define IDC_STATIC_FRAMERATE2           1070
#define IDC_STATIC_GOP1                 1071
#define IDC_STATIC_GOP2                 1072
#define IDC_DEVICE_LIST                 1073
#define IDC_STATIC_STREAMTYPE2          1074
#define IDC_STATIC_MODELTYPE            1074
#define IDC_COMBO_STREAMTYPE2           1075
#define IDC_COMBO_MODELTYPE             1075
#define IDC_STATIC_FPS1                 1076
#define IDC_STATIC_FPS2                 1077
#define IDC_STATIC_BPS1                 1078
#define IDC_STATIC_BPS2                 1079
#define IDC_BUTTON_LENS_INIT            1080
#define IDC_STATIC_GROUP_STREAMFORMAT   1081
#define IDC_STC_GROUP_LOGIN             1082
#define IDC_BUTTON_APPLY                1083
#define IDC_BUTTON_CANCEL               1084
#define IDC_CHECK_SAMEIP                1085
#define IDC_STC_GROUP_LOGIN2            1085
#define IDC_CHECK_SETOSD_IPADD          1086
#define IDC_EDIT_OVERLAYTEXT            1087
#define IDC_MACADDR                     1088
#define IDC_COMBO_POSITION              1088
#define IDC_IPADDR                      1089
#define IDC_CHECK_USED                  1089
#define IDC_GWADDR                      1090
#define IDC_STREAM_PORT_EDIT            1091
#define IDC_HTTP_PORT_EDIT              1092
#define IDC_BUT_RESET                   1093
#define IDC_APPLY                       1093
#define IDC_BUTTON1                     1094
#define IDC_OPEN_XML                    1095
#define IDC_SUBNETMASK                  1102
#define IDC_NET_DHCP                    1103
#define IDC_NET_STATIC2                 1104
#define IDC_STATIC_MASK                 1105
#define IDC_STATIC_IPADDR               1106
#define IDC_STATIC_GATEWAY              1107
#define IDC_STC_PASSWORD                1121
#define IDC_STC_PASSWORD2               1122
#define IDC_STC_OVERLAYTEXT             1122
#define IDC_STC_OVERLAYTEXT2            1123
#define IDC_STC_TEXTPOSITION            1123
#define IDC_STC_LOGIN                   1150
#define IDC_STC_USERID                  1151
#define IDC_STC_GROUP_FUNCTION          1152
#define IDC_USERID                      1153
#define IDC_PASSWORD                    1154
#define ID_SETUP_SETUP                  32771
#define ID_UPGRADE_RETRAY               32772
#define ID_SETUP_OSDSETUP               32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
